using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.Formulator;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Formulator;

[GenerateTypedNameReferences]
public sealed partial class FormulatorWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public Action<Formula>? OnFormulate;

    private readonly SpriteSystem _sprites;

    public FormulatorWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _sprites = _entityManager.System<SpriteSystem>();

        ContentTabs.SetTabTitle(0, Loc.GetString("formulator-window-tab-formulas"));
        ContentTabs.SetTabTitle(1, Loc.GetString("formulator-window-tab-contents"));
    }

    public void ClearContainerInfo()
    {
        ContainerInfo.Children.Clear();

        ContainerInfoName.Text = "";
        ContainerInfoFill.Text = "";
        ContainerView.SetEntity(null);

        ContainerInfo.Children.Add(new Label
        {
            Text = Loc.GetString("formulator-window-no-contents")
        });
    }

    public void UpdateContents(List<FormulaReagentQuantity> contents)
    {
        ReagentList.Children.Clear();

        foreach (var content in contents)
        {
            ReagentList.Children.Add(new ReagentCard(content, _prototypeManager));
        }
    }

    public void UpdateFormulas(List<Formula> formulas)
    {
        FormulaList.Children.Clear();

        foreach (var formula in formulas)
        {
            var card = new FormulaCard(formula, _prototypeManager, _sprites);
            card.OnFormulate += args => OnFormulate?.Invoke(args);
            FormulaList.Children.Add(card);
        }
    }

    public void UpdateContainerInfo(EntityUid uid, ContainerInfo container)
    {
        ContainerInfo.Children.Clear();

        ContainerInfoName.Text = container.DisplayName;
        ContainerInfoFill.Text = container.CurrentVolume + "/" + container.MaxVolume;
        ContainerView.SetEntity(uid);

        if (container.Reagents is {} reagents)
        {
            foreach (var (reagent, quantity) in reagents)
            {
                // Try get to the prototype for the given reagent. This gives us its name.
                var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? p)
                    ? p.LocalizedName
                    : Loc.GetString("formulator-window-unknown-reagent");

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("formulator-window-reagent-quantity", ("quantity", quantity)),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    }
                });
            }
        }

        if (container.Entities is {} entities)
        {
            foreach (var (entity, quantity) in entities)
            {
                var nameLabel = new Label { Text = $"{entity}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("formulator-window-reagent-quantity", ("quantity", quantity)),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    }
                });
            }
        }
    }
}
