using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._DV.Formulator;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Formulator;

[GenerateTypedNameReferences]
public sealed partial class FormulaCard : Control
{
    private static ResPath PillsRsiPath = new("/Textures/_DV/Objects/Specific/Chemistry/pills.rsi");
    private static ResPath BottlesRsiPath = new("/Textures/_DV/Objects/Specific/Chemistry/bottle.rsi");

    public Action<Formula>? OnFormulate;

    public FormulaCard(Formula formula, IPrototypeManager prototypeManager, SpriteSystem sprites)
    {
        RobustXamlLoader.Load(this);
        ReagentBar.MinBarSize = new(15, 0);

        FormulateButton.OnPressed += _ => OnFormulate?.Invoke(formula);

        FormulaNameLabel.Text = formula.Name;
        foreach (var quantity in formula.ReagentQuantities)
        {
            if (!prototypeManager.TryIndex(quantity.Reagent, out var reagent))
                continue;

            ReagentBar.AddEntry(quantity.Quantity.Float(), reagent.SubstanceColor, reagent.LocalizedName);

            var nameLabel = new Label { Text = $"{reagent.LocalizedName}: " };
            var quantityLabel = new Label
            {
                Text = Loc.GetString("formulator-window-reagent-quantity", ("quantity", quantity.Quantity)),
                StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
            };

            FormulaReagents.Children.Add(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                {
                    nameLabel,
                    quantityLabel,
                }
            });
        }

        if (formula is PillFormula pill)
        {
            FormulaTypeLabel.Text = Loc.GetString("formulator-window-type-pill", ("quantity", pill.PillQuantity));

            var specifier = new SpriteSpecifier.Rsi(PillsRsiPath, "pill" + (pill.PillType + 1));
            FormulaTypeTexture.Texture = sprites.Frame0(specifier);
            FormulaTypeTexture.TextureScale = new Vector2(2f, 2f);
            FormulaTypeTexture.Stretch = TextureRect.StretchMode.KeepCentered;
        }
        else if (formula is BottleFormula _)
        {
            FormulaTypeLabel.Text = Loc.GetString("formulator-window-type-bottle");

            var specifier = new SpriteSpecifier.Rsi(BottlesRsiPath, "bottle");
            FormulaTypeTexture.Texture = sprites.Frame0(specifier);
            FormulaTypeTexture.TextureScale = new Vector2(2f, 2f);
            FormulaTypeTexture.Stretch = TextureRect.StretchMode.KeepCentered;
        }
    }
}
