using Content.Shared._DV.Formulator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Formulator;

[GenerateTypedNameReferences]
public sealed partial class ReagentCard : Control
{
    public ReagentCard(FormulaReagentQuantity item, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);

        var reagent = prototypeManager.Index(item.Reagent);

        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = reagent.SubstanceColor };
        ReagentNameLabel.Text = reagent.LocalizedName;
        FillLabel.Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", item.Quantity));
    }
}
